############# Author's search ##########
######## Author: Yan Han
######## Date: May 9, 2023
######## Updated: April 1, 2024
##### Search authors' publication using openAlex data ####
# OpenAlex R Documentation: https://github.com/ropensci/openalexR
# OpenAlex Beta explorer: https://explore.openalex.org/ (the explorer seems not to display all the possible researchers. In ohter words, You shall use API
# The explorer can be only used as a verification/testing purpose!!!
# To generate output for a specific dept/unit, simply change the current working directory at line 34 - 36: getwd() and setwd()

install.packages("remotes")
remotes::install_github("ropensci/openalexR", force=TRUE) 

#install.packages("openalexR") #install.packages("openalexR")  ### use the latest development version due to issue with the production version openalexR 1.10. Waiting for 1.2.0
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("knitr")
install.packages("testthat")
install.packages("readr")
install.packages("readxl")
install.packages("openxlsx")

library(openalexR)
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
library(testthat)
library(openxlsx)
library(readr)

options (openalexR.mailto="yhan@arizona.edu")
getwd()
#setwd("/home/yhan/Documents/UA-datasets/openalexR-test/DOM_Banner")
setwd("/home/yhan/Documents/UA-datasets/openalexR-test/UAL")

######### Step 1 :  Get unit/dept/college authors ######################
######### LDAP search
#LDAP query against ldap.arizona.edu (public, no account required), e.g.
# Via linux terminal and save the result as "ldif"
# > ldapsearch -H ldap://ldap.arizona.edu -D "" -b "o=University of Arizona,c=US" -w -x 'departmentNumber=1705' givenName sn >dept1705.ldif

# To find Dept HR code: log into apps.iam.arizona.edu to search person >> OrgSearch (partent org, child orgs) 
# Example: https://apps.iam.arizona.edu/orgs/ua_orgs/view/1705

# Department of Medicine at College of Medicine (UMC-Tucson): code : 0713
# 1. Get LDAP data by running (we need sn and givenName)
#    > "ldapsearch -H ldap://ldap.arizona.edu -D "" -b "o=University of Arizona,c=US" -w -x 'departmentNumber=0713' sn givenName> dept0713.ldif
# 2. Convert the LDAP data to CSV file (matching_LDAP_authors_names.py contains two function: a) parse ldif to csv; and b) merge csv file by comparing it with Funk's CSV (XLSV converted to CSV), which generates two CSV files: 
#   {dept}.csv = dept LDAP ; {dept}_common.csv = common entries between the {dept}.csv and Funk's CSV
#   This is by Using "common_entries.py" to convert LDIF (LDAP data interchange format) to CSV format. 
#   > "Python common_entries.py" to enter dept name such as "dept0713". 
# 3. run code like below to get two important info: 
#  a) detailed author info logged with name like "author_name.log" and "deptxxx.log" (generated by get_dept_authors_names())
#  b) author and his/her publications in a year, saved as an xlsx file. 
#   In addition, the author's openAlex ID logged with file like "deptxxxx_2023_author.log" (generated by output_dept_autor_works_by_year)
###################################################################
# affiliation_name <- "University of Arizona"
# dept_code <- "dept1704"
# dept_authors_names <- list()
# dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)
# output_dept_author_works_by_year(dept_code, dept_authors_names, 2022)
#######################################################################

# General Note:
# 1. Each author can have 0 or 1, or more OpenAlex IDs. There are three cases:
#  a) An author has 0 id: meaning that there is no matching for the author's name, and affiliation. 
#  b) An author has 1 id:  at least one match.
#  c) An author has >1 ids: This could also happen. e.g.  C. Kent Kwoh has 5 ids. Each one has an affiliation with the University of Arizona. 
#    It seems that certain ids are associated with specific publication year. It is possible these separate ids were generated from different data sources (e.g. repositories) 
 
# 2. Certain authors may not be in the Excels because they did not publish in that specific year 
# For example, Duane Whitaker https://openalex.org/A5025248729 does not have any publications in 2022 and 2023. So this author won't appear in the excel tab)

# 3. I checked over 50% of authors (5,00) from DOM, Banner and UAL depts (code 1701 to 1706) (>50%), and believe that precision = 90% and recall =100%.  
# 4. We are aware of some error-matchings. One way to correct these errors might need to be working with OpenAlex to manually correct them. 



########################## Functions ###########################33
#####################################################
# Function: Calculate works count
#####################################################
calculate_works_count <- function(author_name, affiliation_name, year) {
  # getting data from openAlexR API
  author_from_names <- oa_fetch(entity = "author", search = author_name )
  if (is.null(author_from_names)) {
    author_stats <- NULL
  }
  else {
    # Filter out not "University of Arizona" authors using "affiliation_display_name" column.
    # other filtering fields can be "affiliation_id", "affiliation_ror"
    filtered_authors <- subset(author_from_names, grepl(affiliation_name, affiliation_display_name, ignore.case=TRUE))
    print(filtered_authors)
    
    # If NOT found the author, return NULL
    if (nrow(filtered_authors) == 0 )  {
      author_stats <- NULL
    }
    else {
      # works_count is a list, getting "counts_by_year" column
      works_count  <- filtered_authors$counts_by_year
      print(works_count)
      works_sum_year <- 0
      total_works_sum_year <- 0
      
      # cited_by_count is a list
      cited_by_count <- filtered_authors$cited_by_count
      cited_sum_year <- 0
      total_cited_sum_year <-0
      
      # check the works_count
      for (i in 1:length(works_count)) {
        # Access the data frame within the list
        df <- works_count[[i]]
        
        if (is.data.frame(df)) {
          # Filter the data frame by year
          filtered_df_year <- df[df$year == year, ]
          # Calculate the sum of the filtered 'works_count' column
          works_sum_year <- sum(filtered_df_year$works_count)
          total_works_sum_year <- total_works_sum_year + works_sum_year
          # Calculate the sum of the filtered 'cited_by_count' column
          cited_sum_year <- sum(filtered_df_year$cited_by_count)
          total_cited_sum_year <- total_cited_sum_year + cited_sum_year
          
          # reset this number to 0 after each iteration
          works_sum_year <- 0
          cited_sum_year <- 0
        } else {
          ##### Note: If you see error msg: Error: $ operator is invalid for atomic vectors
          # That means certain works_count  is logical and has no data
          print("This is NOT a dataframe. Data Wrong")
          # set value as -1 for warning message
          Total_sum_of_works = -1
          Total_cited_sum_year = -1
        }
      } # for loop
      
      # Build output dataframe author_stats
      author_stats <-data.frame (
        Name = author_name,
        OpenAlexId = filtered_authors$id,
        Year = year,
        Total_sum_of_works = total_works_sum_year,
        Total_sum_of_cited = total_cited_sum_year
      )
      
      # reset the var after done
      total_works_sum_year <- 0
      total_cited_sum_year <- 0
    } # if
    
    return (author_stats)
  }
}

#####################################################
# Function: Find author via his/her affiliation 
# The matching is done by comparing two fields : affiliation_display_name first, and then affiliations_other
# Para "affiliation_name" is a string for matching var "aff_patterns". This is necessay because 'aff_patterns' can be in multiple formats
# return: the filtered list of authors if matches are found, otherwise logs a message and returns NULL.
# Note: "affiliations_other" can be a string or a vector of strings. So both cases shall be taken care of. 
# For searching other universities, the var "aff_patterns" shall be updated for the correct string 
#####################################################
search_author <- function(author_name, affiliation_name) {
  ### Better matching with a vector of strings for aff_patterns 
  # 1st line: aff_patterns ID, ROR, title and so on on the first line: University of Arizona. https://openalex.org/I138006243
  # 2nd line: Banner (increasing recall),  "I2802412784": Banner Health ID, "I4210124665": Banner - University Medical Center Tucson
  # For Banner, with the 2nd line, the matching authors increased from 81 to 83 for year 2022. 
  
  aff_patterns <- c("https://openalex.org/I138006243", "https://ror.org/03m2x1q45", "University of Arizona", "I138006243", 
              "Banner", "I2802412784", "I4210124665")
  
  base_dir <- file.path("./", "output")
  if (!dir.exists(base_dir)) {
    dir.create(base_dir, recursive = TRUE)
  }
  log_file <- file.path(base_dir, paste0(author_name, ".log"))

  author_from_names <- tryCatch({
    withCallingHandlers({
      oa_fetch(entity = "author", search = author_name)
      #cat(file = log_file, append = TRUE)
    }, warning = function(w) {    # Handle and log the warning
      wrn_msg <- paste0(Sys.time(), " search_author(), Warning: ", author_name, ": ", w$message, "\n")
      cat(wrn_msg, file = log_file, append = TRUE)
      invokeRestart("muffleWarning") # Prevent the warning from being printed to the console
    })
  }, error = function(e) {     # Handle and log the error
    err_msg <- paste0(Sys.time(), " search_author(), Error: ", author_name, ": ", e$message, "\n")
    cat(err_msg, file = log_file, append = TRUE)
    message(err_msg) # Optionally display the error message in the console as well
    return(NULL) # Return NULL to indicate the error condition
  })
  
  tryCatch({
    # Check if any authors were retrieved
  if (!is.null(author_from_names) && nrow(author_from_names) > 0) {
      matches <- rep(FALSE, nrow(author_from_names))
    
      for (i in seq_len(nrow(author_from_names))) {
        display_name_match <- FALSE
        affiliations_other_match <- FALSE
      
      # Check primary affiliation only if the field exists
      if (!is.na(author_from_names$affiliation_display_name[i]) && "affiliation_display_name" %in% names(author_from_names)) {
        display_name_match <- any(sapply(aff_patterns, function(pattern) 
          grepl(pattern, author_from_names$affiliation_display_name[i], ignore.case = TRUE)))
      }
    
        if ("affiliations_other" %in% names(author_from_names) && !is.null(author_from_names$affiliations_other[[i]]) && 
            length(author_from_names$affiliations_other[[i]]) > 0) {
          affiliations_other_match <- any(sapply(author_from_names$affiliations_other[[i]], function(affiliation) {
            any(sapply(aff_patterns, grepl, x = affiliation, ignore.case = TRUE))
          }))
        }
      
      matches[i] <- display_name_match | affiliations_other_match
     } # for loop
    
    filtered_authors <- author_from_names[matches, ]
    if (nrow(filtered_authors) == 0) {
      wrn_msg <- paste0("search_author() ", author_name, " Found, but this author affiliation does NOT match ", affiliation_name, " pattern defined in search_author(). \n")
      cat (wrn_msg, file = log_file, append = TRUE)
    } else {
        return(filtered_authors)
    }
  } else {   # author name no match.  
      wrn_msg <- paste0("search_author() ", author_name, ": NO such author's name found from OpenAlex dataset. \n")
      cat (wrn_msg, file = log_file, append = TRUE)
      return(NULL)
  }}, warning = function(w) {
    wrn_msg <- paste0(Sys.time(), " search_author(), Warning: ", author_name, ": ", w$message, "\n")
    cat(wrn_msg, file = log_file, append = TRUE)
    message(wrn_msg)
  }, error = function(e) {
    err_msg <- paste0(Sys.time(), " search_author(), Error: ", author_name, ": ", e$message, "\n")
    cat(err_msg, file = log_file, append = TRUE)
    #message(err_msg)
    return(NULL) # Return NULL to indicate the error condition
  })
  
}

#author_name <- "Jose Gonzalez"   # ? https://openalex.org/A5016903118

#affiliation_name <- "Banner"
#author_from_names_direct <- oa_fetch(entity = "author", search = author_name) #6429 matches. 
#author_from_names <- search_author(author_name, "University of Arizona")

# 2024-02-07: "Vivian Kominos" has no affiliation info at all
author_name <- "Vivian Kominos"
affiliation_name <- "University"
author_from_names <- oa_fetch(entity = "author", search = author_name)
UAresult1 <- search_author(author_name, affiliation_name)

##### Function: Get works from author ORCID and year
get_works_from_orcid_by_year <- function(orcid, publication_year) {
  if (is.null(orcid)) {
    stop("ORCID cannot be NULL.")
  }
  
  author_works <- tryCatch({
    oa_fetch(
      entity = "works",
      author.orcid = orcid, 
      publication_year = publication_year,
      verbose = TRUE
    )
  }, error = function(e) {
    message ("get_works_from_orcid_by_year(): An error occured: ", e$message)
    return (NULL)
  })
  return(author_works)
}

################################################################
##### Function: Get works from OA's author id and publication year #########
### Para: dept_code, author_id (best option), year
### return: author works
get_works_from_authorid_by_year <- function(dept_code, author_id, year) {
  
  base_dir <- file.path("./", "output", dept_code)
  if (!dir.exists(base_dir)) { dir.create(base_dir, recursive = TRUE) }
  log_file <- file.path(base_dir, paste0(author_id, "_", year, ".log"))
  
  if (is.null(author_id)) {  # Check if author_id is NULL
    err_msg <- paste0(Sys.time(), "get_works_from_authorid_by_year(), Error: ", author_id, "is NULL.")
    cat(err_msg, file = log_file, append = TRUE)
    message(err_msg)
    return (NULL)
  }

  # Attempt to fetch author works and handle potential errors
  author_works <- tryCatch({
    oa_fetch(
      entity = "works",
      author.id = author_id,  
      publication_year = year,
      verbose = TRUE
    )
  }, error = function(e) {
    err_msg <- paste0(Sys.time(), "get_works_from_authorid_by_year(), Error: ", author_id, "in ", year, e$message)
    cat(err_msg, file = log_file, append = TRUE)
    message(err_msg)
    return(NULL)
  })
  return(author_works)
}

# Example. get author obj

author_name <- "Bekir Tanriover"
author_id <- "a5016874418"
# working
author<- oa_fetch(entity = "authors", identifier = author_id,  verbose = TRUE)
# Not working "author.ids" is not a valid field
# author<- oa_fetch(entity = "authors", author.id = author_id,  verbose = TRUE)
# Not working "identifier" 
work <- oa_fetch(entity = "works",  
         author.id = author_id, 
         publication_year = '2023',   verbose = TRUE)

#author_works <- get_works_from_authorid_by_year(dept_code, author_id, '2023')

# Get author obj using OpenAlex's authorid
### This function is to verify author_id and its affiliations contain correct org
### Para: author_id (manual)
### Return: author obj 
get_au_from_authorid <-function(author_id) {
  # Attempt to fetch author and handle potential errors
  author<- tryCatch({
    oa_fetch(
      entity = "authors",
      identifier = author_id,
      #author.id = author_id, 
      verbose = TRUE
    )
  }, error = function(e) {
    err_msg <- paste0(Sys.time(), "get_au_from_authorid(), Error: ", author_id, "in ", year, e$message)
    #cat(err_msg, file = log_file, append = TRUE)
    message(err_msg)
    return(NULL)
  })
  return(author)
}

#author_works <- oa_fetch(  entity = "works",   author.id = "a5016874418",   publication_year = 2023,   verbose = TRUE )
author_id <- "a5016874418"
author_test <- get_au_from_authorid(author_id)

################### Function ######################
### parameter: dept_code and affiliation
### return: dept authors name after using search_author() dept_authors_name is a list containing author dfs (each df is an author obj containing his/her name, id, affiliation,etc)
###         log file
get_dept_authors_names <- function(dept_code, affiliation_name) {
  # Construct the base directory path based on dept_code
  base_dir <- file.path("./", "output", dept_code)
  if (!dir.exists(base_dir)) { dir.create(base_dir, recursive = TRUE)  }
  
  file_path <- sprintf("%s.csv", dept_code)
  #file_path <- sprintf("%s_common.csv", dept_code)
  log_file_path <- file.path(base_dir, paste0(dept_code, ".log"))
  
  if (!file.exists(file_path)) { stop("get_dept_authors_names(): ", dept_code, "CSV File not found: ", file_path) }
  
  LDAPdata <- read_csv(file_path, show_col_types = FALSE)
  
  if (nrow(LDAPdata) == 0) {
    err_msg <- paste0("get_dept_authors_names(): ", dept_code, "CSV file has no data. \n")
    cat(err_msg, file = log_file_path, append = TRUE)
    message(err_msg)
    return(list())  # Return an empty list
  }
  
  authors_names <- LDAPdata$cn
  dept_authors_names <- list() 
  
  for (i in 1:length(authors_names) ) {
    # Access the current row
    author_result_affiliation <- NULL 
    
    author_name <- NULL
    author_name <- authors_names[i]
    print (paste(author_name, affiliation_name, "!!!"))
  
    tryCatch({
      author_result_affiliation <- search_author(author_name, affiliation_name)
      log_time <- paste("\n***** get_dept_authors_names() calling search_author(): ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), 
                        author_name, " Author affiliation:", affiliation_name, "\n", sep=" ")
  
      #author_status <- NULL
      #author_stats <- calculate_works_count(author_name, affiliation_name, 2022)
      print(author_result_affiliation)
      if (!is.null(author_result_affiliation)) {
        # Temporarily capture output of dput to a variable
        dput_str <- capture.output(dput(author_result_affiliation))
        cat(log_time, file=file(log_file_path, "a"), sep="\n")
        cat(dput_str, file=file(log_file_path, "a"), sep = "\n")
      } else {
        cat(log_time, file=file(log_file_path, "a"), sep="\n")
        cat("get_dept_authors_names(): search_author(author_name, affiliation_name) return NULL !!!\n", file = log_file_path, append = TRUE)
      }
      
    }, warning = function(w) {
      wrn_msg <- paste("get_dept_authors_names(): Warning: ", log_time, dept_code, author_name, w$message, "\n")
      cat(wrn_msg, file = log_file_path, append =TRUE)
      message(wrn_msg)
    }, error = function(e) {
      err_msg <- paste("get_dept_authors_names(): Error: ", log_time, dept_code, author_name, e$message, "\n")
      cat(err_msg, file = log_file_path, append = TRUE)
      message(err_msg)
    })
    
    # Check if any of the results are NULL or have zero rows; handle accordingly
    if (is.null(author_result_affiliation) || nrow(author_result_affiliation) == 0) {
      author_result_affiliation <- NA  # or some other placeholder value
    }
    #if (is.null(author_stats) || length(author_stats) == 0) {
    #  author_stats <- NA  # or some other placeholder value
    #}
    # Append the results to the list
    dept_authors_names[[i]] <- data.frame(author_name = author_name, 
                                        author_result_affiliation = author_result_affiliation) 
                                        #author_stats = author_stats)
  }
  # dept_authors_names is a list containing author_dfs (each df is an author obj)
  return (dept_authors_names) 
  
}

###################################################################################
### Function: output author's works by its oa author_id and year. 
### It is necessary to do so, because this author_works df are very complex (a df of dfs)
### It is a small db, cannot be represented by a single sheet of XLSX
### Para: dept_code : the dir to saved to)
###       author_name: author_name.log to output log
###       author_id and year: two real parameters to pass to get_works_from_authorid_by_year(dept_code, author_id, year) 
### return: after calling get_works_from_authorid_by_year(), return xlsx file containing the author's works

output_works_by_authorid_by_year <- function(dept_code, author_name, author_id, year, base_dir = ".") {
  if (!requireNamespace("dplyr", quietly = TRUE)) { 
    stop("output_works_by_authorid_by_year(): dplyr package is not installed. Please install it using install.packages('dplyr').")
  }
  if (!requireNamespace("writexl", quietly = TRUE)) {
    stop("output_works_by_authorid_by_year(): writexl package is not installed. Please install it using install.packages('writexl').")
  }
  if (is.null(author_id)) {
    stop("output_works_by_authorid_by_year(): author_id cannot be NULL.")
  }
  
  base_dir <- file.path("./", "output", dept_code)
  if (!dir.exists(base_dir)) {
    dir.create(base_dir, recursive = TRUE)
    print(paste("Directory created at:", base_dir))
  }
  print(paste("Current working directory:", getwd())) 
  
  log_file <- file.path(base_dir, paste0(author_name, "_", year, ".log")) # Define log file path
  
 ######## calling get_works_from_authorid_by_year() #####################
 author_works <- get_works_from_authorid_by_year(dept_code, author_id, year)
  if (is.null(author_works) || length(author_works) == 0) {
    err_msg <- paste0(Sys.time(), " output_works_by_authorid_by_year() ", author_name,  " ", author_id,  " ", year, " NO works found!")
    cat(err_msg, file = log_file, append = TRUE)
    return(NULL)
  }
  # add additional filter to filter affiliation col for the institution.
  # In an ideal situation, this does not need if the author_id is 100% accurate
  # In current situation, there are same-name authors works mixing together!!!!!
  
  
  # Processing column "author" to get au_display_name (then put it in a new col) and get affiliation (then put it into a new col)
  if(!is.null(author_works$author)) {
    #authors_names <- sapply(author_works$author, get_au_display_names, USE.NAMES = FALSE)
    author_works$authors_name <- lapply(author_works$author, get_au_display_name)
    author_works$affiliation  <- lapply(author_works$author, get_au_affiliation_raw)
  } else { 
    # If author_works$author is NULL, handle accordingly
    author_works$authors_name <- "NA"
    author_works$authors_affiliation <- "NA"
    message("output_works_by_authorid_by_year(): author_works$author is NULL. 'authors_name' and 'authors_affiliation' column set to NA.")
  }
  
  ### Processing column "ids" to get PMID
  if(!is.null(author_works$ids)) {
    author_works$pmid <- lapply(author_works$ids, get_pmid)
  } else { 
    # If NULL, handle accordingly
    author_works$pmid <- "NA"
    message("output_works_by_authorid_by_year(): author_works$PMID is NULL. 'PMID' column set to NA.")
  }
   
  #!!!!! Very important: Need to handle NA value in OpenAlex data. Otherwise, it will crash other functions such as writexlsx()!!!
  # The best way so far is to "as.character" and then replace NUL. 
  author_works <- author_works %>%
    mutate(across(everything(), as.character)) %>%
    mutate(across(everything(), ~replace_na(., "N/A")))
  
  # Make the col "authors_name" as the first column
  author_works <- author_works %>% select(authors_name, affiliation, everything())
  
  # Exclude certain columns.
  # author_works <- select(author_works, -c (counts_by_year, concepts, ab, so_id, issn_l, pdf_url, first_page, last_page, volume, issue, 
  #  is_oa, is_oa_anywhere, oa_url, any_repository_has_fulltext, grants, cited_by_api_url, referenced_works, related_works, is_paratext, is_retracted) )
  
  # Define the columns 
  desired_columns <- c("authors_name", "affiliation", "id", "display_name", "publication_date", "so", 
                       "host_organization", "url", "license", "version", "oa_status", "language", 
                       "cited_by_count", "publication_year", "pmid", "doi", "type")
  
  # Check which of the desired columns exist in 'author_works'
  existing_columns <- desired_columns[desired_columns %in% names(author_works)]
  author_works <- select(author_works, all_of(existing_columns))
  
  # limit each column to 32767 because writexl cannot handle more than 32767 chars
  author_works <- author_works %>%
    mutate(across(where(is.character), ~ifelse(nchar(.) > 32767, substr(., 1, 32767), .)))
  
  print(author_works)
  
  # Generating the filename
  filename <- paste0(gsub("[[:punct:]]", "", author_name), "_", year, ".xlsx")
  full_path <- file.path(base_dir, filename)
  
  writexl::write_xlsx(author_works, path = full_path)
  message("output_works_by_authorid_by_year(): File '", full_path, "' has been created.")
}


#################### get author's display_name from "author" col #### 
### Para: author_info : col "author" from openAlex's works
### Return: author$au_display_name
get_au_display_name <- function(author_info) {
  # Check if author_info is a data frame and contains the 'au_display_name' column
  if (is.data.frame(author_info) && "au_display_name" %in% names(author_info)) {
    # Concatenate 'au_display_name' values into a single string
    names_concatenated <- paste(author_info$au_display_name, collapse = ", ")
    return(names_concatenated)
  } else {
    # Return NA if author_info is not a data frame or 'au_display_name' column is missing
    return("get_au_display_name(): author_info is not a dataframe or au_display_name is missing")
  }
}

##################### get author's affiliation from "author" col ###
### Para: author_info: col "author" from openAlex's works
### Return: author$au_affiliation_raw
get_au_affiliation_raw <- function(author_info) {
  # Check if author_info is a data frame and contains the column
  if (is.data.frame(author_info) && "au_affiliation_raw" %in% names(author_info)) {
    names_concatenated <- paste(author_info$au_affiliation_raw, collapse = "; ")
    return(names_concatenated)
  } else {
    # Return NA if author_info is not a data frame or 'c' column is missing
    return("get_au_affiliation_raw(): author_info is not a dataframe or c col is missing")
  }
}


################### get PMID from "ids" col #####
### Para: col "ids" from openAlex's works
### Return: pmid
get_pmid <- function(ids) {
  # Check if "pmid" key exists
  if("pmid" %in% names(ids)) {
    pmid_url <- ids["pmid"]
    #numeric_pmid <- gsub("https://pubmed.ncbi.nlm.nih.gov/", "", named_urls["pmid"])
    return(pmid_url)
  } else {
    # Return NA if there's no "pmid" key
    return(NA)
  }
}

# Since lapply returns a list and each element is just a single PMID, you might want to simplify this to a vector
pmids_vector <- unlist(pmids)

################# Test ##############################

#### Dept of Medicine (HR code: 0713 and 0788) Test date: 2024-01-24 
##### Test cases: data is not uniformed.  
author_works <- get_works_from_authorid_by_year("test", "a5082148123", 2022)
getwd()
output_works_by_authorid_by_year("test", "Keith A Joiner", "a5082148123", 2022)

# Apply the function to each element in the list (assuming multiple data frames could be in the list)
#authors_names <- sapply(author_works$author, get_au_display_names, USE.NAMES = FALSE)
author_works$authors_name <- lapply(author_works$author, get_au_display_name)
author_works$authors_affiliation <- lapply(author_works$author, get_au_affiliation_raw)
# Apply the function to each element in the 'pmid' list
author_works$pmid <- lapply(author_works$ids, get_pmid)

str(pmid)
class(pmid)

# Error in x[is.na(x)] <- na.string : replacement has length zero. Why? 
### Sara Centuori no affiliation. need to send to openAlex
author_works <- get_works_from_authorid_by_year("test", "a5080182165", 2022)
output_works_by_authorid_by_year("test", "Sara Centuori", "a5080182165", 2022)

# Bekir Tanriover: https://openalex.org/authors/a5016874418 
author_name <- "Bekir Tanriover"
author_id <- "a5016874418"
publication_year <- "2023"
dept_code <-"test"
author_works <- get_works_from_authorid_by_year(dept_code, author_id, publication_year)
UAresult1 <- search_author(author_name, affiliation_name)
output_works_by_authorid_by_year(dept_code, author_name, author_id, publication_year) 

# H.-H Sherry Chow
# issues: Two DOIs issued for figure s1, s2, and s3,  table s1, s2, s3 and s4 (v1 )
author_name <-"H. H. Sherry Chow"
author_id <- "a5018050941"
dept_code <- "test"
author_works <- get_works_from_authorid_by_year(dept_code, author_id, publication_year)
output_works_by_authorid_by_year(dept_code, author_name, author_id, publication_year) 


############################################################################
#### Now getting every author's works by each dept ###
### Function: 
### Parameter: dept_authors: a list contaning authors info, including author_name and author_id. author_id is used for acurate matching to openAlex 
### return: calling get_works_from_authorid_by_year() and output_works_by_authorid_by_year() 
######################################################################################
output_dept_author_works_by_year <- function(dept_code, dept_authors, year) {
  if (is.null(dept_code) || !nzchar(dept_code)) {
    stop("Department code ('dept_code') must be provided and cannot be empty.")
  }
  
  base_dir <- file.path("./", "output", dept_code)
  if (!dir.exists(base_dir)) {
    dir.create(base_dir, recursive = TRUE)
  }
  getwd() 
  
  log_file   <- file.path(base_dir, paste0(dept_code, "_", year, ".log")) # Define log file path
  log_file_author <- file.path(base_dir, paste0(dept_code, "_", year, "_author.log")) # Define log file path
  
  if (length(dept_authors) == 0) {
    msg <- paste0("output_dept_author_works_by_year(): ", Sys.time(), dept_code, ": ", dept_authors_names, " in ", year, ": No authors found for this department.")
    write(msg, file = log_file, append = TRUE)
    message(msg)
    return()  # Exit the function early
  }
  
  for (i in seq_along(dept_authors)) {
    current_df <- dept_authors[[i]]
    author_name <- current_df$author_name
    author_id <- current_df$author_result_affiliation.id
    
    # output author_name and author_id to a log file and to the terminal
    msg <- paste(author_name, author_id)
    write(msg, file = log_file_author, append = TRUE)
    message(msg)
    
    tryCatch({
      if (!is.null(author_id) && nzchar(author_id)) {
        get_works_from_authorid_by_year(dept_code, author_id, year)
        output_works_by_authorid_by_year(dept_code, author_name, author_id, year, base_dir)
      } else {
        msg <- paste("output_dept_author_works_by_year():", Sys.time(), author_name, ": Skipping due to NULL author_id\n")
        message(msg)
        write(msg, file = log_file, append = TRUE)
      }
    },  warning = function(w) {
      wrn_msg <- paste("output_dept_author_works_by_year(): ", Sys.time(), author_name, " year ", year, " : Warning: ", w$message)
      write(paste(wrn_msg, file = log_file, append = TRUE))
      message(wrn_msg)      
    }, error = function(e) {
      err_msg <- paste("output_dept_author_works_by_year(): ", Sys.time(), author_name, "year ", year, " : Error: ", e$message)
      write(err_msg, file = log_file, append = TRUE)
      message(err_msg)
    })
    }
}

#######################################

# 2024-07-28

author_name <- "Jarrod Mosier"
affiliation_name <- "University of Arizona"
author_from_names <- oa_fetch(entity = "author", search = author_name)
UAresult1 <- search_author(author_name, affiliation_name)
author_id <- "https://openalex.org/A5002885008"
dept_code <- "test"
author_works <- get_works_from_authorid_by_year(dept_code, author_id, 2022)
output_works_by_authorid_by_year(dept_code, author_name, author_id, 2022)

author_works <- get_works_from_authorid_by_year(dept_code, author_id, 2023)
output_works_by_authorid_by_year(dept_code, author_name, author_id, 2023)






#dept_code <- readline(prompt = "Please enter the department code: ")
#affiliation_name <- readline(prompt = "Please enter the affiliation: ")

### 2024-01-25: Affiliation issues: 
### [1] "Tejo K Vemulapalli University" Error in is.factor(x) : object 'affiliation_display_name' not found In addition: Warning messages:
###  1: In oa_request(oa_query(filter = filter_i, multiple_id = multiple_id,       Not found!
### 2024-01-26: opened an issue with openAlexR https://github.com/ropensci/openalexR/issues/196 and can now find from "affiliations_other"

# No works found for year 2023
# No work found for year 2022
author_name <- "Tejo K Vemulapalli"
author_id <-"a5023323706" 
affiliation_name <- "University of Arizona"
author_from_names <- oa_fetch(entity = "author", search = author_name)
UAresult1 <- search_author(author_name, affiliation_name)
output_works_by_authorid_by_year(dept_code, author_name, author_id, 2022)
output_works_by_authorid_by_year(dept_code, author_name, author_id, publication_year)

# NULL 
author_name <- "Vivian Kominos"
affiliation_name <- "University"
author_from_names <- oa_fetch(entity = "author", search = author_name)
UAresult1 <- search_author(author_name, affiliation_name)

### Error: 1 match. But I think the match was wrong. Geoffrey is with U.S. Renal care (did not find he is associated with UArizona or Banner) 
### search_author() relies on openAlex data. 
author_name <- "Geoffrey A. Block" # should be "Geoffrey D. Block" https://openalex.org/A5076006182  ?? 
author_id <- "A5076006182"
affiliation_name <- "University of Arizona or Banner"
author_from_names <- oa_fetch(entity = "author", search = author_name)
UAresult1 <- search_author(author_name, affiliation_name)
output_works_by_authorid_by_year(dept_code, author_name, author_id, 2022)
output_works_by_authorid_by_year(dept_code, author_name, author_id, 2023)

### These have no affiliation with "University". https://openalex.org/authors/a5019422724
author_name <- "Lise Alschuler"  
affiliation_name <- "University of Arizona"
author_from_names <- oa_fetch(entity = "author", search = author_name)
# 2 obs found. One has affiliations_other (UA ID: I138006243)  One does not have any affiliation info. 
author_from_names$affiliations_other
UAresult1 <- search_author(author_name, affiliation_name)

#### Banner: 
##### Aaron Scott: 2022: 21 articles?? 
#### I am very positive: This is wrong: alternative name Jesse Aaron. Jesse Aaron is not associated with University of Arizona. see https://www.biorxiv.org/content/10.1101/2022.07.07.499185v2
### see https://www.molbiolcell.org/doi/10.1091/mbc.E21-10-0506
### However, oa records says that Aaron Scott is with University of Arizona' 'Imaging Center'

# step2: get dept author name and filtering 
# step 3: get authors works based on the names and affiliation

#### Note: Publication date may vary on: Received date, accepted date, published date, 
### sometimes a publication date in 2022, but listed as published in 2023.
### Note: OpenAlex data (author at least) is way better than ASM (check Debra Stern) or 
affiliation_name <- "Unversity of Arizona"
year <- 2022

### 2024-04: For UA Libraries

### Verified by author: 
# 2023: Wrong author: 
# 1. Jack Oliver: https://doi.org/10.21203/rs.3.rs-3367979/v1 (Reason: authors_name as Jeffrey C. Oliver) 
# 2. Mary Feeney: https://openalex.org/authors/A5051274338 (Reason: Two persons, same name: there is the same-name author in ASU.
# 3. Michael Brewer: (Michael Henry: Different person)
# 4. Cynthia M. Elliott:  (Reason: Two authors, same name at UA)
# 5. Kimberly Chapman: (Reason: Two authors, same name at UA)

# 2023: Missing
# 1. Lacey, S., Clement, K., Nataraj, L., & Pagowsky, N. (2023). Making Publishing Less Painful: Shifting to a Relational Peer-Review Process. Urban Library Journal, 29(2). https://academicworks.cuny.edu/ulj/vol29/iss2/2
# 2. Pagowsky, N., Freundlich, S., Gammons, R., & Drabinski, E. (2023). Teaching from the outside: Inclusive pedagogy and the adjunct instructor. In Brown, R., Foster, E., Nichols, J., Mallon, M., Santiago, A., & Seale, M. (Eds.) Exploring inclusive and equitable pedagogies: Creating space for all learners, (pp. 567-588). Chicago, IL: ACRL Press. [UArizona repository copy: http://hdl.handle.net/10150/668022]


# 2022: 
# 1. Missing:  https://earlymodernstudiesjournal.org/review_articles/transcribing-recipe-manuscripts-online-v-b-380-and-the-whats-in-a-recipe-undergraduate-research-project-at-penn-state-abington/
# Froehlich, Heather, Marissa Nicosia, and Christina Riehman-Murphy. “Transcribing Recipe Manuscripts Online: V.b. 380 and the ‘What’s in a Recipe?’ Undergraduate Research Project at Penn State Abington.” Celebrating Ten Years of the Early Modern Recipe Online Collective/ 2022 English Department/University of Texas, Arlington 8 (2022): 23–41.
# 2. Jennifer Martin: https://openalex.org/authors/a5002098356 (same-name author)
# https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011461 
# Jennifer Martin: https://api.openalex.org/works/W4310749693
# 

  
#### Special handling of authors whose affiliations are not UArizona (because of their last publications were in their last positions)
author_id <-"a5079884839"  # Jennifer Church-Duran
publication_year <- "2022" 

get_works_from_authorid_by_year("test", author_id, "2021") # libguide, type = "article"
output_works_by_authorid_by_year("test", "test-name", author_id, "2021")



### dept1701:

affiliation_name <- "University of Arizona"
dept_code <- "dept1701"  # dept1701: 22 people
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2023)

# Tara: https://openalex.org/authors/a5004453378
author_name <- "Tara Radniecki"
author_id <- "a5004453378"
author_test <- get_au_from_authorid(author_id )
author_test$affiliations_other
output_works_by_authorid_by_year(dept_code, author_name, author_id, 2023)

# Michael Brewer https://openalex.org/A5009411264
# Michael Brewer https://openalex.org/A5047553232
# Michael Brewer https://openalex.org/A5081779788


# Note: 
## 1. Staff generally do not have publications. By including them in the search, it reduces precision due to matching errors.
## 2. Admin with faculty status typically are affiliated with their previous institutions, unless they published recently with the current ones. As a result, they most likely cannot be found via search_author() 
## 3. Certain authors may have incorrect linkage with other institutions. in this case, portion of the author's info and works are incorrect. 
## 4. In unusual cases, an institution may have two authors have exactly the same first and last name. Search name is the most powerful tool to match author. The use of authors name is firstname+lastname, while middle name is disgarded. 

# Error: 
# 1. Amanda Gutierrez: to the same name author (who has affiliation wrongly linked to UArizona) 
# David Anderson (correct: None). Reason: same name author
# 2. Armando Arroyo
# 3. Michael Brewer: Linked to the same name author "Michael Brewer Henry https://openalex.org/A5009411264 
# 4. Aengus Anderson (David Anderson) : 
# Special handling:
# Harriett Green: https://openalex.org/authors/a5052644624
# Tara Radniecki: https://openalex.org/authors/a5004453378 
# Jennifer Church-Duran: a5079884839:  https://openalex.org/authors/a5079884839

affiliation_name <- "University of Arizona"
dept_code <- "dept1703"  # dept1703: 22 people
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2023)

### Error logs: 
# 1. Cynthia Elliott (correct: https://openalex.org/A5079703497). reason: her affiliation (UArizona) is also linked at the same name author (https://openalex.org/authors/A5077224399: affiliations_other: "https://openalex.org/I138006243")
# 2. Elizabeth Miller (no publications). reason: her affiliation is linked to UArizona. https://openalex.org/A5021488636

### Correct: all the rest

### Special handling:
# 1. Stacey Erdman (associated with ): a5036184879 : (Beloit College, Northen Illinois U?)
# 2. Dana Lema: https://openalex.org/authors/a5078878293  : San Jose State U ? 
# 3. Daricus Larry (correct: https://openalex.org/authors/a5064179467). reason: no affiliation

author_id <- "A5077224399"
author_test <- get_au_from_authorid(author_id )
author_test$affiliation_display_name
author_test$affiliations_other


affiliation_name <- "University of Arizona"
dept_code <- "dept1704" : # 36 people
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2023)
# Error logs:
# Lauren Williams (correct: None). reason: linked to another author @ https://openalex.org/A5065909147 because that author has affiliations with https://openalex.org/I138006243
# Samantha Stevens (correct: None). reason: linked to another author@ https://openalex.org/A5059242519 (same as the above)
# Devin Johnson (correct: None). reason: linked to another author @ https://openalex.org/A5016809644 (same as the above)
# Katherine Young (correct: None). reason: linked to another author @ https://openalex.org/A5063412207 (same as the above)
# The rest are correct. 
# check dept1704.log for everyone's detailed info
# check dept1704_2022_author.log for author and associated ID.



### 2024-03: For UAL-RE: see dept1705.log
### 2024-03-14: Author's middle name can cause "not found" (e.g. Kimberly A Chapman, Niamh A Wallace). So need to remove middle name  
### Author error: Anthony Sanchez : Mapped to C. A. Sanchez 
#### Error log: 
# 1. Heather Froehlich (correct: https://openalex.org/A5009648082 ) Matched correctly but wrong affiliation Reason: affiliated with Penn State U. because she worked there. 
# 2. Fernando Rios (correct: ?? ORCID. wrong: id https://openalex.org/A5027526343)  Reason: same name. Note: Did not find Fernando Rios ID. 
# 3. Anthony Sanchez (correct:) Reason: same name
# 4. Kimberly Chapman (correct: A5078704068): two person at the same institution: 1 ID. Reason: There are two Kimberly: exactly the same name at UArizona. https://openalex.org/authors/A5078704068 : Steward Observatory. The other at UA Libraries
# 5. Daniel Martin (Use name: Jim Martin) (correct: https://openalex.org/authors/a5047129465) :  Reason: same name. Note: linked to wrong institution
# 6. Yan Han  (correct: https://openalex.org/A5056855636) https://orcid.org/0000-0001-9518-2684). Reason: linked to wrong same-name person (which has a wrong affiliation). 
#    work error: https://openalex.org/works/w2580214781 (author is Yan Han?, error)

### Correct linkage:
# 1. Megan Senseney: ORCID and Scopus ID
# 2. Ellen Dubinsky: ORCID and Scopus ID
# 3. Vicktoria Wilcox (no publications)
# 4. Jeffrey Oliver: ORCID
# 5. Alana Varner: (no publications) 
# 6. Elizabeth Kline: ORCID
# 7. Cheryl Casey: 
# 8. Niamh Wallace: 

dept_code <- "dept1705"  # dept1705: 14 people
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2023)


# https://openalex.org/W4386348049 (arXiV author data error)
author_name <- "Yan Han"
affiliation_name <- "University of Arizona"
author_from_names <- oa_fetch(entity = "author", search = author_name)
UAresult1 <- search_author(author_name, affiliation_name)

# Tara: https://openalex.org/authors/a5004453378
author_name <- "Jim Martin"
author_id <- "a5004453378"
author_test <- get_au_from_authorid(author_id )
author_test$affiliations_other
output_works_by_authorid_by_year(dept_code, author_name, author_id, 2023)


author_name <- "Heather Froehlich"
author_id <- "A5009648082"  # affiliated with Penn State https://openalex.org/A5009648082
UAresult1 <- search_author(author_name, affiliation_name)
author_test <- get_au_from_authorid(author_id )
author_test$affiliations_other
output_works_by_authorid_by_year(dept_code, author_name, author_id, 2023)


# ~100% correct Except J. Mayer
affiliation_name <- "University of Arizona"
dept_code <- "dept1706"  # dept1706 (SpeColl): 19 people
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2023)
# Error logs: 
# 
# Note: these authors have no data?! 
# Stephen Hussman (No record)
# Lisa Duncan
# Erika Castano
# Joseph Diaz
 
dept_code <- "dept1707"  # dept1707 (SLE): 18 people
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2023)

# Error logs:
# Ping Situ (correct: https://openalex.org/A5066336894) reason: also linked to another author @ South China University of Technology
# Mary Feeney (correct: https://openalex.org/authors/a5051274338) reason: linked to another same-name author @ ASU

# To be fixed (not error)
# Nicole Hennig: (MIT) not Gail Hennig  https://staging.openalex.org/authors/a5036080329

dept_code <- "dept1709"  # dept1707 (TeSS): 0 (centralization progject)
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)

dept_code <- "dept6804"  # dept6804 (HSL): 0 (centralization progject)
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2023)

### dept0701: 1 match (all matched)
### 2022: 1 author: Keith A Joiner
### 2023: 1 author found: Keith A Joiner
dept_code <- "dept0701"
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_code, affiliation_name)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_code, dept_authors_names, 2023)

### dept0712: 1 match (All matched: Lisa O'Neill)
dept_name <- "dept0712"
dept_authors_names <- list()
getwd()
dept_authors_names <- get_dept_authors_names(dept_name, affiliation_name)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2023)

### 2024-02-14:
### dept0713: 49 matches (all except 1 not matched with Funk's list)
### 2022: 40 authors works found
### 2023: 42 authors found
### Rachana Shroff: 2023: 78 records: checked: ~70 DOIs issued for table, table s3. (Type as "article"). 
# Similar cases like H.H. Sherry for American Association for Cancer Research (on figshare.com). The same publishing practice
### Checked: Bekir Tariover, Bhaskar Banerjee, Janet Funk, Sairam Parthasarathy, Reubender Randhawa
### Error: Bhaskar Banerjee https://arxiv.org/abs/2306.06717 (same name)
### 

dept_name <- "dept0713"
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_name, affiliation_name)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2023)

### dept0721: 1 match (HH Sherry Chow). 
### 2022: 2 authors found (HH Sherry Chow and Rebecca Crocker)
###       Rebecca Crocker: verified (Center for Health Disparities Research (CHDR), University of Arizona Health Sciences, Tucson, AZ, USA)
### 2023: 2 authors found (All)
###       Rebecca Crocker: verified (Cancer Center, College of Medicine, University of Arizona, Tucson, AZ 85724, USA)
### Funk's list: Crocker, Robert (LDAP: Rebecca Crocker)
### Funk's list: Centuori, Sara (LDAP: None )
dept_name <- "dept0721"
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_name, affiliation_name)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2023)

### dept0723: 1 matches (All matched. Guerra, Stefano) 
### 2022 & 2023: 2 authors found (Stefano Guerra, and LDAP name: Debra Stern (Not in Funk's list)
### 2022 & 2023: Debra Stern: verified: Asthma and Airway Disease Research Center, The University of Arizona, Tucson, Arizona, USA
dept_name <- "dept0723"
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_name, affiliation_name)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2023)

### dept0747: 1 matches (All matched)
# Guadalupe Carr": author_id not found for this author. check error log
# 2023: Kevin Moyanahan verified
dept_name <- "dept0747"
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_name, affiliation_name)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2023)

### dept0782: 0 matches (Funk's list: Fantry, George)
# The CSV file is empty: dept0782_common.csv                                                                                                                                                                              
dept_name <- "dept0782"
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_name, affiliation_name)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2023)

### dept0788: 7 matches (All matched)
# Error: Robert Crocker (mixed two diff authors. )
dept_name <- "dept0788"
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_name, affiliation_name)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2023)

### dept0795: 0 match (Funk's list: John Galgiani)
# John Galgiani is in dept0713
# The CSV file is empty: dept0795_common.csv                                                                                                                                                                              
dept_name <- "dept0795" 
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_name, affiliation_name)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2023)

### Banner- University Medical Center Tucson  ID: i4210124665
### Banner Health ID: i2802412784. Using a vector of strings increased recall.
### Some of Banner authors have affiliation of "University of Arizona", "University of Arizona Cancer Center". 
### Affiliations: Using vector of string (not containing "Banner": found 83 authors' works. There are 148
### 
### 2022: Avin Aggarwal, Indu Partha, Saad Kubba, Olivia Hung (affiliation is Sarver Heart Center, UA, Banner?) Mathew Hutchinson (Mahesh Balakrishnan not in Funk's list) verified 
### 2022: Hemanth K. Gavini,
### Not error: duplicated DOIs (Mathew Hutchinson 2023 works in both Pubmed and Wiley)
### Error: 2022: Gefforey A. Block. >>> should be Gefforey D Block. 
### Error: 2022: Hong Seok Lee (same name): London: https://doi.org/10.1002/adma.202203310 https://doi.org/10.1002/adma.202270240
### Error: 2023: Hong Seok Lee (same name): Korea: https://pubs.acs.org/doi/10.1021/acssensors.2c01086 https://pubmed.ncbi.nlm.nih.gov/36798505
### Error: Jose Gonzalez: (reason?) 2023: https://doi.org/10.56470/978-9942-627-93-3 https://doi.org/10.1016/j.annonc.2023.10.013
### Error: data error: Sarah Tariq not in the arXiv's article metadata(https://doi.org/10.48550/arxiv.2306.07713), 
### Error: Randall Wong (alt name: Ryan Wong) https://openalex.org/authors/A5078075711
### 2023: Verified:
### Abd Assalam Qannus, Akshay Amaraneni, Ernest Vina, Indu Partha, Lauren Estep, Olivia Hung, Sarah Tariq, Venkata Rokkam, Sharad Khurana
### 2024-02-17:
### Error: https://openalex.org/W4214607846 (type: aritlce) "display_name" the same "so" = "image" and  https://openalex.org/W4221051350 (so = "treanscript" )
### Error: https://openalex.org/W4206158552 and https://openalex.org/W4288786850 (display_name = "Contributors, type = book-chapter)

dept_name <- "dept_banner" 
affiliation_name <- "Banner" 
dept_authors_names <- list()
dept_authors_names <- get_dept_authors_names(dept_name, affiliation_name)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2022)
output_dept_author_works_by_year(dept_name, dept_authors_names, 2023)


##############################################################################

### Banner faculty. No LDAP match??
library(readxl)

file_path <- "Funk_faculty_list.xlsx"
# read the "Banner" sheet
data_sheet_by_name <- read_excel(file_path, sheet="Banner")
head(data_sheet_by_name)

# Banner has no LDAP, so making a new dept with Banner's authors by combing the sheet's LAST NAME and FIRST NAME
data_sheet_by_name$cn <-paste(data_sheet_by_name$`FIRST NAME`, data_sheet_by_name$`LAST NAME`, sep = " ")
new_csv <-data.frame(cn = data_sheet_by_name$cn)
head(new_csv)

write.csv(new_csv, "dept_banner_common.csv", row.names = FALSE)

# run the Banner as a UA's dept
dept_banner <- list()
# Use "Arizona" to see how many authors have  no affiliation of "Arizona"
dept_banner <- get_dept_author_data("dept_banner", "Arizona")
### results:
#[1] "Anthony Witten Arizona"
# Column 'affiliation_display_name' not found in the data.

dept_banner <- list()
# Use "University" to see how many authors have  no affiliation of "University"
dept_banner <- get_dept_author_data("dept_banner", "University")

#### OpenAlex records:

### 2024-01-30: 
# 1. Hong Lee https://deptmedicine.arizona.edu/profile/hong-seok-lee-md-mph
# publications: https://www.ncbi.nlm.nih.gov/myncbi/101LmwjcFptkp/bibliography/public/ 
# His works list has "Lee H", "Lee HS", "Seok Lee H", publishing works from 2008 - latest 2020
# Also his affiliation with NLM is "Department of Cardiovascular Diseases, Mayo Clinic, Scottsdale, AZ, USA."! 

# (note: NLM author search link is not correct with over 70,000 results. Many authors have names such as "Lee H", "Lee HH", "Lee HK")

# openAlex records: searching "Hong S. Lee" returns 12 works from 1990 - 2022. None is from him. 
# Note: Same name, different person

# 2. Amanpreet S. Bains, https://deptmedicine.arizona.edu/profile/amanpreet-s-bains-md
# MD, Assistant Professor, Medicine, Medical Director, Clinical Decision Unit, Division of Inpatient Medicine
# Degrees: MD: University of the West Indies Faculty of Medical Sciences, 2002. Residency: Wilson Memorial Medical Center Internal Medicine
# openAlex records: https://openalex.org/authors/A5005342862 or https://openalex.org/authors/a5076616077 (not the same person)


# To display the list certain fields. to output 

#############################################################
# check to see if openAlexR has the latest entities in OpenAlex (OpenAlex updated its data model(Entities) in June 2023)
# Before April 2023: they are [1] "works"        "authors"      "venues"       "institutions" "concepts"    
# If not, need to use openalexR developer's version
oa_entities()

############################## Testing Cases #######################

############################## ORCID as filter ####################################
# Download all works published by a set of authors using ORCIDs
# use author.orcid as a filter
# https://api.openalex.org/authors/https://orcid.org/0000-0001-9518-2684
### NOTE: May 2023, Not all the works are there, NEED TO discuss with OpenAlex. Most likely the disambigation alg not working well. https://docs.openalex.org/api-entities/authors
### NOTE: Aug 2023, OpenAlex has a new author data with a new disambiguation model. It is getting better but there are still some bugs/errors.
### Example: Aug 2023, there are 80 works associated with "0000-0001-9518-2684". About 40 works are NOT authored by me. (My works are all written in English. For some reason, these works are NOT pulled from ORCID)
### NOTE: Jan 2024, ORCID 0000-0001-9518-2684 returns "no records found!"
works_from_orcids <- oa_fetch(
  entity = "works",
  #author.orcid = c("0000-0001-9518-2684"),  
   author.orcid = c("0000-0001-6187-6610", "0000-0002-8517-9411"),
  verbose = TRUE  
) 


########################### Author matching criteria: 1) starting with ORCID; 2) using latest publication's affiliations 3) 
#### July 2023:  Bekir affiliation shows "Columbia University", which is wrong. He (2009-2013) is at Columbia University, then he moved to UT Southwestern, and now he is at UA
#### Aug 11, 2023: Bekir affiliation shows "University of Arizona", which is correct now. 
author_from_names <- oa_fetch(entity = "author", search = "Bekir Tanriover" )
author_from_names$id

### Aug 11, 2023: Results contain wrong info (Haitong Tai: https://openalex.org/A5060511275 ) affiliation not updated yet (probably based on last publication's affiliation)
author_from_names <- oa_fetch(entity = "author", search = "Haw-chih Tai")

#### This authorID upgrade does show my work/citation seems right with affiliation. There are 692 obs of "Yan Han". Most have ORCIDs. 
### Aug 2023: Yan Han: affiliation Jilin university. Wrong. 
### April 2024: https://openalex.org/A5056855636 (correct, but mixed with other people)
author_from_names <- oa_fetch(entity = "author", search = "Yan Han")
author_from_names <- search_author("Yan Han", "University of Arizona")

#### This upgrade found and contains Hong Cui's ID and correct affiliation. but needs further filtering via affiliation
author_from_names <- oa_fetch(entity = "author", search = "Hong Cui")



# R does not have LDAP packages??
# clean all objects from the environment to start
rm(list = ls())

################### Test data
test_data_UAL_authors     <- c("Yan Han", "Ellen Dubinski", "Fernando Rios", "Ahlam Saleh")
test_data_COM_authors     <- c("Phillip Kuo", "Bekir Tanriover", "Ahlam Saleh")
test_data_COM_Tucson_authors <- c("Che Carrie Liu", "Robert M. Aaronson", "Alexa Aasronson", "Mohammed Abbas", "")
test_data_science_authors <- c("Marek Rychlik", "Ali Bilgin", "Beichuan Zhang")
test_data_ischool_authors <- c("Hong Cui")
test_data_others          <- c("Leila Hudson", "Mona Hymel")
test_data_not_updated_authors <-c("Karen Padilla", "Haw-chih Tai")

test_data_affiliation <- c("University of Arizona")
test_data_year <- c("2022", "2021", "2020", "2012")

#### Some testing first 
author_from_names <- oa_fetch(entity = "author", search = "Bekir Tanriover" )
## openalexR 1.10 package failed on the search below. 
author_from_names <- oa_fetch(entity = "author", search = test_data_not_updated_authors[1] )
author_from_names <- oa_fetch(entity = "author", search = "Haw-chih Tai")

# Read test data from CSV: column: LastName, FirstName
file_path <- "test_authors_COM_0713.csv"    #"test_authors_1.csv"
data <- read.csv(file_path) 

# create an empty vector
data_unit_staff <- list()
# iterate 
for (i in 1:nrow(data)) {
  firstname <- as.character(data[i, "givenName"])
  lastname <- as.character(data[i, "sn"])
  data_unit_person <- paste(firstname, lastname)
  data_unit_staff  <- c(data_unit_staff, data_unit_person)
}


################################ Finding Author's name, affiliation, sum of works, and total citations ##############################
# Filter Doc: https://github.com/ropensci/openalexR/blob/main/vignettes/articles/Filters.Rmd

#### 1. First do a fuzzy search on author's name ##########################
###  do NOT use display_name because it requires an exact match. Often there are multiple middle names for an author
author_from_names <- oa_fetch(entity = "author",
                               search = test_data_COM_authors[2] ) ### "search" syntax allows fuzzy search for middle name
# first checking
if (!is.null(author_from_names)) {
  print("author found")
  # Filter out not "University of Arizona" authors using "affiliation_display_name" column.
  # other filtering fields can be "affiliation_id", "affiliation_ror"
  filtered_authors <- subset(author_from_names, grepl("University of Arizona", affiliation_display_name, ignore.case=TRUE))
  # Showing the results
  filtered_authors |>
    show_authors() |>
    knitr::kable()
  if (nrow(filtered_authors) == 0 )  {
    print("The filtered_authors dataframe is empty")
  }
  # output works_count in 2022
  # works_count is a list
  works_count  <- filtered_authors$counts_by_year
  print(works_count)

  # cited_by_count
  cited_by_count <- filtered_authors$cited_by_count

  # Testing data
  works_sum_year <- 0
  total_works_sum_year <- 0
  cited_sum_year <- 0
  total_cited_sum_year <-0

  ### Handle empty list
  df <-works_count[[20]]
  if (is.null(df)) {
    print("Emement is null")
  } else {
    print("CONT")
  }

  filtered_df_2022 <- df[df$year == 2022, ]
  # Loop through each data frame in the list
  length(works_count)
  for (i in 1:length(works_count)) {
    # Access the data frame within the list
    df <- works_count[[i]]

    if (is.data.frame(df)) {
    ##### Note: If you see error msg: Error: $ operator is invalid for atomic vectors
    # That means certain works_count  is logical and has no data
  ########## Building block for count each year
    # Filter the data frame for the year 2022
    filtered_df_2022 <- df[df$year == 2022, ]
    # Calculate the sum of the filtered 'works_count' column
    works_sum_2022 <- sum(filtered_df_2022$works_count)
    total_works_sum_2022 <- total_works_sum_2022 + works_sum_2022
    # Calculate the sum of the filtered 'cited_by_count' column
    cited_sum_2022 <- sum(filtered_df_2022$cited_by_count)
    total_cited_sum_2022 <- total_cited_sum_2022 + cited_sum_2022

    # reset this number to 0
    works_sum_2022 <- 0
    cited_sum_2022 <- 0
    } else {
      print("This is NOT a dataframe. Data wrong")
    }
}

  total_cited_sum_2022 <- 0
  total_works_sum_2022 <- 0
}

########################## TESTING PEOPLE ####################
### Format: Name: Year: Works/Cited



############# College of Medicine Tucson Test Date:  2023-05-14: If test in a different date, result may vary
#### U of Arizona College of Medicine Faculty and Staff Directory https://medicine.arizona.edu/directory/faculty-staff
#### Phillip Kuo: 2022: 30 and 133: 26 IDs
####            : 2023-07: after authorID updates: 17 and 330
author_name <- "Phillip H. Kuo"
affiliation_name <- "University"
author_result_fuzzy       <- oa_fetch(entity = "author", search = author_name)
author_result_affiliation <- search_author(author_name, affiliation_name )
author_stats              <- calculate_works_count(author_name, affiliation_name, 2022)

### Bekir Tanriover returns 5 openAlex ID: 2022: works 11, cited 166; 2021: works 4 cited 167
###: 2023-07: after authorID updates: NULL (??? error )
### 2023-08: After authorID updates: correct affiliation: 2022: 16 and 170
author_name <- "Bekir Tanriover"
author_result_fuzzy       <- oa_fetch(entity = "author", search = author_name)
author_result_affiliation <- search_author(author_name, affiliation_name )
author_stats              <- calculate_works_count(author_name, affiliation_name, 2022)



author_stats <- calculate_works_count(test_data_COM_authors[2], test_data_affiliation[1], test_data_year[1])
author_stats <- calculate_works_count(test_data_COM_authors[2], test_data_affiliation[1], test_data_year[2])
###  Ahlam Saleh returns 0, because of "One list does not contain a valid OpenAlex collection" ????
author_stats <- calculate_works_count(test_data_COM_authors[3], test_data_affiliation[1], test_data_year[1])

###### College of Medicine Tucson
author_stats <- calculate_works_count(test_data_COM_Tucson_authors[1], test_data_affiliation[1], test_data_year[1])
author_stats <- calculate_works_count(test_data_COM_Tucson_authors[2], test_data_affiliation[1], test_data_year[1])
author_stats <- calculate_works_count(test_data_COM_Tucson_authors[3], test_data_affiliation[1], test_data_year[1])
author_stats <- calculate_works_count(test_data_COM_Tucson_authors[4], test_data_affiliation[1], test_data_year[1])
author_stats <- calculate_works_count(test_data_COM_Tucson_authors[5], test_data_affiliation[1], test_data_year[1])


######## Science
### June 2023: Marek Rychlik returns : works 0, cited 11
### Aug 2023: Good result: works 35, cited 502
author_name <- "Marek Rychlik"
author_result_fuzzy       <- oa_fetch(entity = "author", search = author_name)
author_result_affiliation <- search_author(author_name, affiliation_name )
author_stats              <- calculate_works_count(author_name, affiliation_name, 2022)

### Ali Bilgin: works 4, cited 187
### June 2023: Showing 2 results. The other searches show one combined result
### Aug 2023: 2 results: "University of Arizona Medical Center" and "University of Arizona". Need to combine 
author_name <- "Ali Bilgin"
author_result_fuzzy       <- oa_fetch(entity = "author", search = author_name)
author_result_affiliation <- search_author(author_name, affiliation_name )
author_stats              <- calculate_works_count(author_name, affiliation_name, 2022)

####### iSchool
### Hong Cui: NOT found: 2022: 
### June 2023: Showing 1 results. 
### Aug 2023: showing 2 results: one with ORCID, and the other shows none. Need to combine 
author_name <- "Hong Cui"
author_result_fuzzy       <- oa_fetch(entity = "author", search = author_name)
author_result_affiliation <- search_author(author_name, affiliation_name )
author_stats              <- calculate_works_count(author_name, affiliation_name, 2022)

###### Others
### Leila Hudson: 2022: 0/2
### Aug 2023: good result.
author_name <- "Leila Hudson"
author_result_fuzzy       <- oa_fetch(entity = "author", search = author_name)
author_result_affiliation <- search_author(author_name, affiliation_name )
author_stats              <- calculate_works_count(author_name, affiliation_name, 2022)

# Error in works_count[[i]] : subscript out of bounds
author_stats <- calculate_works_count(test_data_others[2], test_data_affiliation[1], test_data_year[1])


##########################################################
#### testing all authors in College of Medicine - Tucson ###
# 10 people per line
# Author's name only contain First name and Last name.
# Author's middle name is not included due to index often does not contain such.
test_data_COM_Tucson_authors <- c("Che Liu", "Robert Aaronson", "Alexa Aaronson", "Joy Abaidoo", "Stephanie Abalos", "Mohammed Abbas", "Adnan Abbasi",  "Kristopher Abbate", "Michelle Abbate", "Lara Abbottt",
                                  "Gebran Abbound", "Mazin Abdaigadir", "Adel Abdallah", "Arwa Abdel-Raheem", "Yasmeen Abdulrahman", "Kalkidan Abebe", "Michael Abecassis", "Anne Abel", "Ty Abel", "Yulia Abidov",
                                  "Richard Ablin", "Ahmed Aboul-Nasr", "Arin Aboulian", "Suzanne Abrahamson", "Amber Abrams", "Artyom Abramyan", "Edward Abril", "Anas Husni Mohamad Abu Assi", "Laila Zaid", "Joe Abuhakmeh",
                                  "Xiaohong Zhang", "Hui Zhang")

### Including all faculty and staff at https://medicine.arizona.edu/directory/faculty-staff
rm(unit_authors_list)

unit_authors_list <- list(author_stats)
unit_authors_list_org_arizona <- list(author_stats)
#author_stats <-calculate_works_count(test_data_COM_Tucson_authors[1], "University of Arizona",2022)
#unit_authors_list <- append(unit_authors_list, list(author_stats))
#unit_authors_list


##### Test specific unit 
authors <- data_unit_staff    # Here is COM_0713

#### Retrieving one author at a time.
for (author in authors) {
  print(author)
  # Setting org_name can be critical for the # of results got.
  # If org_name = "", there will be many unrelated people.
  # College of Medicine OpenAlex data some do not have affiliation with University of Arizona.
  org_name = "university"
  
  # filter results using org_name
  temp_author_status <- calculate_works_count(author, org_name, 2022)
  temp_author_status
  unit_authors_list <- append(unit_authors_list, list(temp_author_status))
  }

unit_authors_list_org_arizona <- unit_authors_list


###########################################

# search and filter using openAlex institution ID "affiliation_id"
author2_from_names <- oa_fetch(entity = "author", search = "Yan Han" ) ### "search" syntax allows fuzzy search for middle name
filtered_author2 <- subset(author2_from_names, grepl("https://openalex.org/I138006243", affiliation_id, ignore.case=TRUE))

# display_name and filter using ROR "affiliation_ror"
author3_from_names <- oa_fetch(entity = "author", display_name = c("Bekir Tanriover", "Ahlam Saleh") ) ### "search" syntax allows fuzzy search for middle name
filtered_author3 <- subset(author3_from_names, grepl("https://ror.org/03m2x1q45", affiliation_ror, ignore.case=TRUE))

##### Testing with multiple authors
unit_authors_names <- list( "Phillip Kuo", "Bekir Tanriover", "Ahlam Saleh")
unit_authors_list <- list()

# 1. Filter author one by one using his/her name using fuzzy search option
for (unit_author in unit_authors_names) {
  # find an author's name using fuzzy search
  unit_author_from_names <- oa_fetch(entity = "author", search = unit_author)
  # create an empty df
  unit_author <- data.frame()
  # filter author based on his/her affiliation_display_name
  unit_author <- subset(unit_author_from_names, grepl("University of Arizona", affiliation_display_name, ignore.case=TRUE))

  # Append the author (df) as an element to the list
  unit_authors_list <- append(unit_authors_list, list(unit_author))

  # Clear unit_author
  unit_author <- NULL

}

# 2. Output

for (i in 1:length(unit_authors_list)) {
 print(unit_authors_list[[i]])
  # Loop through each element in the author list to calculate the sum of publications
  author_works_count <-sum (unit_authors_list[[i]]$works_count)
  output_string <- "Researcher" + unit_authors_list[[i]]$display_name + "Year" + counts_by_year

  }

